eureka:
  instance:
    #静态页面，默认/info，做快捷测试用
    status-page-url-path: /hi?name=testBy[sc-client-feign]

server:
  port: 8882
#服务别名
spring:
  application:
    name: sc-client-feign
#feign自带熔断器，默认关闭，可选开启
feign:
  hystrix:
    enabled: true

# 设置hystrix超时时间（毫秒） ，默认只有2秒，设置为50秒，根据实际业务重试次数而定。gateway也应该加
hystrix:
  command:
    HelloFeignClient#testHystrix:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9000
    default:
      execution:
#        timeout:
#          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 5000
# 开启自带hystrix, 加ribbon配置才起起效
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

#修改Hystrix的默认切点，端口/hystrix
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /