server:
  port: 8279

spring:
  datasource:
    url: jdbc:h2:D:\YH\test\ureport;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;
    driver-class-name: org.h2.Driver
#    password: 123
    username: root
    schema: classpath:db/pgsql.sql
  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-allow-others: true
  #    url: jdbc:postgresql://localhost:5432/ureport
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: yanghan
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,file:${uploadfile.path}
  #文件上传
  servlet:
    # 文件上传大小限制
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

#log日志配置
logging:
  #文件输入绝对路径
  file: /opt/ureport/log/out.log


# ureport 数据库源
ureport:
  provider:
    postgresql:
      prefix: yh-
      disabled: false
