### 基础镜像，使用alpine操作系统，openjkd使用8-jdk-alpine
FROM openjdk:8-jdk-alpine

# 添加jar包
ADD jar/client-ribbon.jar client-ribbon.jar

#启动容器时的进程
ENTRYPOINT ["java","-jar","/client-ribbon.jar"]
#暴露端口
EXPOSE 8883
