version: '3'

services:
  ureport:
    # 构建镜像名称，没有build属性默认从远程仓库获取
    image: ureport
    # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
    build:
     context: ./
     dockerfile: Dockerfile-ureport
    ports:
     - 8279:8279