version: '3'

networks:
  ureport:
    driver: bridge

services:
  ureport:
    # 容器名
    container_name: ureport
    # 重启策略: 容器退出时总是重启容器
    restart: always
    # 构建镜像名称，没有build属性默认从远程仓库获取
    image: ureport
    # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
    build:
     context: ./
     dockerfile: Dockerfile-ureport
    environment:
     TZ: Asia/Shanghai
    ports:
     - 8279:8279
    volumes:
     # 实际绝对路径（若写相对路径前缀$pwd）
      - /home/java-web/ureport/config:/config
    networks:
      - ureport