### 基础镜像，使用alpine操作系统，openjkd使用8-jdk-alpine
FROM openjdk:8-jdk-alpine

#系统编码
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
#处理alpine字体缺少，导致excel格式无法导出
RUN echo -e "https://mirror.tuna.tsinghua.edu.cn/alpine/v3.4/main\n\
https://mirror.tuna.tsinghua.edu.cn/alpine/v3.4/community" > /etc/apk/repositories
RUN apk --update add curl bash ttf-dejavu && \
      rm -rf /var/cache/apk/*
#RUN apk add --update ttf-dejavu fontconfig && rm -rf /var/cache/apk/*
#应用构建成功后的jar文件被复制到镜像内，名字也改成了app.jar
ADD jar/ureport.jar ureport.jar
ENV PARAMS=

#启动容器时的进程
#ENTRYPOINT ["java","-jar","/ureport.jar","--spring.profiles.active=h2"]
ENTRYPOINT ["java","-jar","/ureport.jar", " $PARAMS"]


#暴露端口
EXPOSE 8279