eureka:
  instance:
    #静态页面，默认/info，做快捷测试用
    status-page-url-path: /hi?name=testBysc-feign

server:
  port: 8882
#服务别名
spring:
  application:
    name: sc-client-feign
#feign自带熔断器，默认关闭，可选开启
feign:
  hystrix:
    enabled: true
#修改Hystrix的默认切点，端口/hystrix
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /

hystrix:
  command:
    default:
      execution:
#        timeout:
#          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 50000

