eureka:
  instance:
    #静态页面，默认/info，做快捷测试用
    status-page-url-path: /hi?name=testBysc-ribbon
server:
  port: 8883
spring:
  application:
    name: service-ribbon
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /